### ISSUE TITLE
Blender 4.1 Compatibility

### ISSUE THREAD

**Issue by Thane5** [MarshmallowCirno/XRay_Selection_Tools#2]
When using x-ray select in edit mode with Blender 4.1 i get this error:

```
Python: Traceback (most recent call last):
  File "C:\Users\thatsmyname\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\space_view3d_xray_selection_tools\mesh_ot\mesh_ot_box.py", line 352, in invoke
    self.init_overlays = gather_overlays(context)  # save initial x-ray overlay states
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thatsmyname\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\space_view3d_xray_selection_tools\functions\mesh_modal.py", line 10, in gather_overlays
    "backwire_opacity": context.space_data.overlay.backwire_opacity,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'View3DOverlay' object has no attribute 'backwire_opacity'
```

**Comment by kloworks** [comment]
I try it today and it give me error.
hope it get support for 4.1

**Comment by Thane5** [comment]
there is a fix where you have to modify `mesh_modal.py` , see here: https://blenderartists.org/t/x-ray-selection-tools/1212316/464
